version: '3'
services:
  app1:
    image: khushi26/app1
    container_name: app1
    volumes:
      - .:/users/tmp
    ports:
      - "5000:5000"
    networks:
      - app1netw
  app2:
    image: khushi26/app2
    container_name: app2
    volumes:
      - .:/users/tmp
    ports:
      - "5001:5001"
    networks:
      - app1netw

networks:
  app1netw:
    driver: bridge